"""Bootstrap helpers for first-time application setup."""
from __future__ import annotations

from pathlib import Path
from typing import Dict

from loguru import logger
from sqlalchemy import select
from sqlalchemy.exc import SQLAlchemyError

from app.db.models import Base, User
from app.db.session import _build_engine, build_postgres_url, session_scope

ENV_PATH = Path(".env")

DEFAULT_CONFIG: Dict[str, str] = {
    "DATABASE_HOST": "localhost",
    "DATABASE_PORT": "5432",
    "DATABASE_NAME": "boroboys_music",
    "DATABASE_USER": "postgres",
    "DATABASE_PASSWORD": "postgres",
    "SECRET_KEY": "",
    "SPOTIFY_CLIENT_ID": "",
    "SPOTIFY_CLIENT_SECRET": "",
    "SPOTIFY_REDIRECT_URI": "http://localhost:8000/auth/callback",
    "SPOTIFY_SCOPE": "playlist-modify-private playlist-read-private user-read-email",
    "FRONTEND_REDIRECT_URL": "http://localhost:5173/",
    "LASTFM_API_KEY": "",
    "LASTFM_SHARED_SECRET": "",
    "LASTFM_USERNAME": "",
    "LOG_LEVEL": "INFO",
    "ENABLE_SCHEDULER": "true",
}


def serialize_env(config: Dict[str, str]) -> str:
    lines = ["# Generated by Boro Boys setup", ""]
    for key, value in config.items():
        lines.append(f"{key}={value}")
    return "\n".join(lines)


def write_env_file(config: Dict[str, str], *, overwrite: bool = False) -> Path:
    if ENV_PATH.exists() and not overwrite:
        raise FileExistsError(".env already exists. Pass overwrite=True to replace it.")
    content = serialize_env(config)
    ENV_PATH.write_text(content, encoding="utf-8")
    return ENV_PATH


def initialize_database(database_url: str) -> None:
    try:
        engine = _build_engine(database_url)
        Base.metadata.create_all(engine)
    except SQLAlchemyError as exc:
        logger.error("Failed to initialize database: {}", exc)
        raise


def create_or_update_admin_user(
    *,
    database_url: str,
    username: str,
    display_name: str,
    password_hash: str,
    spotify_user_id: str | None = None,
    lastfm_username: str | None = None,
) -> User:
    with session_scope(database_url=database_url) as session:
        statement = select(User).where(User.username == username)
        user = session.scalar(statement)
        if user:
            user.display_name = display_name
            user.role = "admin"
            user.password_hash = password_hash
            user.spotify_user_id = spotify_user_id
            user.lastfm_username = lastfm_username
        else:
            user = User(
                username=username,
                display_name=display_name,
                role="admin",
                password_hash=password_hash,
                spotify_user_id=spotify_user_id,
                lastfm_username=lastfm_username,
            )
            session.add(user)
        session.flush()
        session.refresh(user)
        return user


def build_database_url_from_config(config: Dict[str, str]) -> str:
    return build_postgres_url(
        host=config["DATABASE_HOST"],
        port=int(config["DATABASE_PORT"]),
        database=config["DATABASE_NAME"],
        username=config["DATABASE_USER"],
        password=config["DATABASE_PASSWORD"],
    )
