"""add round submission limit

Revision ID: 5b6a2a18fa5e
Revises: 9b9ede2bc902
Create Date: 2026-09-05 14:37:37.880731

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5b6a2a18fa5e"
down_revision: str | None = "9b9ede2bc902"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rounds", sa.Column("submission_limit", sa.Integer(), nullable=False))
    op.create_check_constraint(
        "ck_rounds_submission_limit_nonnegative", "rounds", "submission_limit >= 0"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_rounds_submission_limit_nonnegative", "rounds", type_="check")
    op.drop_column("rounds", "submission_limit")
    # ### end Alembic commands ###
