"""add attribution guessing game

Revision ID: 800f9880f496
Revises: e690bbf0ab1b
Create Date: 2026-09-14 00:17:55.397067

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "800f9880f496"
down_revision: str | None = "e690bbf0ab1b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attribution_games",
        sa.Column("round_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("correct_count", sa.Integer(), nullable=True),
        sa.Column("total_count", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["round_id"], ["rounds.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("round_id", "user_id", name="uq_attribution_games_round_user"),
    )
    op.create_index(
        op.f("ix_attribution_games_round_id"), "attribution_games", ["round_id"], unique=False
    )
    op.create_index(
        op.f("ix_attribution_games_user_id"), "attribution_games", ["user_id"], unique=False
    )
    op.create_table(
        "attribution_guesses",
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.Column("submission_id", sa.UUID(), nullable=False),
        sa.Column("guessed_contributor_id", sa.UUID(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["game_id"], ["attribution_games.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["guessed_contributor_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["submission_id"], ["submissions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "game_id", "submission_id", name="uq_attribution_guesses_game_submission"
        ),
    )
    op.create_index(
        op.f("ix_attribution_guesses_game_id"), "attribution_guesses", ["game_id"], unique=False
    )
    op.add_column(
        "rounds", sa.Column("attribution_reveal_delay_seconds", sa.Integer(), nullable=True)
    )
    op.create_check_constraint(
        "ck_rounds_attribution_reveal_delay_nonnegative",
        "rounds",
        "attribution_reveal_delay_seconds >= 0",
    )
    op.add_column(
        "series", sa.Column("default_attribution_reveal_delay_seconds", sa.Integer(), nullable=True)
    )
    op.create_check_constraint(
        "ck_series_attribution_reveal_delay_nonnegative",
        "series",
        "default_attribution_reveal_delay_seconds >= 0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_series_attribution_reveal_delay_nonnegative", "series", type_="check")
    op.drop_column("series", "default_attribution_reveal_delay_seconds")
    op.drop_constraint("ck_rounds_attribution_reveal_delay_nonnegative", "rounds", type_="check")
    op.drop_column("rounds", "attribution_reveal_delay_seconds")
    op.drop_index(op.f("ix_attribution_guesses_game_id"), table_name="attribution_guesses")
    op.drop_table("attribution_guesses")
    op.drop_index(op.f("ix_attribution_games_user_id"), table_name="attribution_games")
    op.drop_index(op.f("ix_attribution_games_round_id"), table_name="attribution_games")
    op.drop_table("attribution_games")
    # ### end Alembic commands ###
