"""add oidc login attempts

Revision ID: 9b9ede2bc902
Revises: 885c829a7ae7
Create Date: 2026-09-05 14:34:02.940694

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9b9ede2bc902"
down_revision: str | None = "885c829a7ae7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oidc_login_attempts",
        sa.Column("state_hash", sa.String(length=128), nullable=False),
        sa.Column("nonce_hash", sa.String(length=128), nullable=False),
        sa.Column("nonce_ciphertext", sa.Text(), nullable=False),
        sa.Column("code_verifier_ciphertext", sa.Text(), nullable=False),
        sa.Column("return_path", sa.String(length=2048), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("state_hash", name="uq_oidc_login_attempts_state_hash"),
    )
    op.create_index(
        op.f("ix_oidc_login_attempts_expires_at"),
        "oidc_login_attempts",
        ["expires_at"],
        unique=False,
    )
    op.add_column(
        "server_sessions", sa.Column("oidc_id_token_ciphertext", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("server_sessions", "oidc_id_token_ciphertext")
    op.drop_index(op.f("ix_oidc_login_attempts_expires_at"), table_name="oidc_login_attempts")
    op.drop_table("oidc_login_attempts")
    # ### end Alembic commands ###
