"""add provider link attempts

Revision ID: b84d86fc3b25
Revises: 5b6a2a18fa5e
Create Date: 2026-09-05 14:53:04.014648

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b84d86fc3b25"
down_revision: str | None = "5b6a2a18fa5e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "external_link_attempts",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "provider",
            postgresql.ENUM("SPOTIFY", "LASTFM", name="externalprovider", create_type=False),
            nullable=False,
        ),
        sa.Column("state_hash", sa.String(length=128), nullable=False),
        sa.Column("code_verifier_ciphertext", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("state_hash", name="uq_external_link_attempts_state_hash"),
    )
    op.create_index(
        op.f("ix_external_link_attempts_expires_at"),
        "external_link_attempts",
        ["expires_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_external_link_attempts_expires_at"), table_name="external_link_attempts")
    op.drop_table("external_link_attempts")
    # ### end Alembic commands ###
