"""add notification preferences and reminder tracking

Revision ID: ba80cf6b4e85
Revises: a1e6d7c9b2f4
Create Date: 2026-09-09 23:19:32.821937

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ba80cf6b4e85"
down_revision: str | None = "a1e6d7c9b2f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "round_members",
        sa.Column("declined_further_submissions_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "rounds", sa.Column("reminder_48h_sent_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "rounds", sa.Column("reminder_24h_sent_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("notify_reminder_emails", sa.Boolean(), server_default=sa.true(), nullable=False),
    )
    op.add_column(
        "users",
        sa.Column(
            "notify_round_published_emails", sa.Boolean(), server_default=sa.true(), nullable=False
        ),
    )
    op.alter_column("users", "notify_reminder_emails", server_default=None)
    op.alter_column("users", "notify_round_published_emails", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "notify_round_published_emails")
    op.drop_column("users", "notify_reminder_emails")
    op.drop_column("rounds", "reminder_24h_sent_at")
    op.drop_column("rounds", "reminder_48h_sent_at")
    op.drop_column("round_members", "declined_further_submissions_at")
    # ### end Alembic commands ###
